### ISSUE TITLE
dashboard.zuul.ansible.com SSL certificates expired on 2020-02-22

### ISSUE THREAD

**Issue by ssbarnea** [ansible/project-config#356]
Certificate on https://dashboard.zuul.ansible.com/ is expired and this fully broke github integration. I was not able to spot any SSL config in public repo, I suppose manual  intevention is needed.

@pabelanger

**Comment by pabelanger** [comment]
Thanks, I the cert actually gets reobtained very 90days from letsencrypt, however there is a bug in the script that doesn't reload nginx properly. I've done it manually for now, and will work on properly fixing to Monday.

**Comment by ssbarnea** [comment]
Was the reloading bug fixed or we should keep this open as it will happen again in ~2 months from now? If it is fixed, I am happy to close it.

**Comment by goneri** [comment]
I believe this has been addressed. Thanks for the issue @ssbarnea.
